package com.webkreator.qlue.view.canoe.corpus;

import com.webkreator.qlue.view.Canoe;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The payload catalogue.
 *
 * <p>Each family names what it is trying to reach, so a case declares intent rather than pasting a
 * string.
 *
 * <p>Adding a variant to a family widens every case that uses that family — which strengthens the
 * <em>coverage</em> but does not establish a <em>verdict</em>. A newly added payload inherits the
 * case's default verdict without anyone having reviewed it, which is exactly the "ledger rots into a
 * bug rubber-stamp" failure the plan warns about. Two things guard against it: {@code
 * XssCase.Builder.overrideFamily} lets a case state a verdict for a whole family at once, and
 * {@code VerdictEvaluator} independently derives the observed verdict and fails when the ledger
 * disagrees. The second is the real guard; the first is convenience.
 *
 * <p>Two conventions matter for the browser tier:
 *
 * <ul>
 *   <li>Executable payloads call {@link #SENTINEL_FUNCTION}, which the browser tier exposes on the
 *       page. {@code alert()} is used only where the point is specifically to test dialog handling.
 *   <li>Network payloads target {@link #SENTINEL_HOST}. {@code .invalid} is reserved by RFC 2606 and
 *       can never resolve, so a detector miss degrades to a connection failure rather than a real
 *       outbound request. The browser tier additionally intercepts and aborts these.
 * </ul>
 *
 * <p>One family from the plan is deliberately absent: {@code BUFFER_RESIDUE_PREFIX} is a template
 * prefix rather than a payload value, so it is generated by {@code BufferResidueTest} (T22).
 */
public final class Payloads {

    /** Exposed on the page by the browser tier; calling it records script execution. */
    public static final String SENTINEL_FUNCTION = "__canoePwned";

    /** RFC 2606 reserved TLD: never resolves, so a missed detector cannot reach a real host. */
    public static final String SENTINEL_HOST = "attacker.invalid";

    // ------------------------------------------------------------------
    // The baseline
    // ------------------------------------------------------------------

    /**
     * The differential oracle's control value: same shape as a payload, but composed only of
     * characters every encoder passes through untouched, so rendering with it produces the document
     * the template author intended.
     */
    public static final Payload INERT_MARKER = payload("INERT_MARKER", "marker", "CANOEMARKERAAAA",
            "nothing - the baseline the differential oracle compares against");

    // ------------------------------------------------------------------
    // Body-context injection
    // ------------------------------------------------------------------

    public static final Payload TAG_IMG_ONERROR = payload("TAG_BREAKOUT", "img-onerror",
            "<img src=x onerror=" + SENTINEL_FUNCTION + "('tag')>",
            "body-context tag injection");

    public static final Payload TAG_SCRIPT = payload("TAG_BREAKOUT", "script-element",
            "<script>" + SENTINEL_FUNCTION + "('tag')</script>",
            "body-context script element injection");

    public static final Payload TAG_SVG_ONLOAD = payload("TAG_BREAKOUT", "svg-onload",
            "<svg onload=" + SENTINEL_FUNCTION + "('tag')>",
            "body-context injection through a foreign-content element");

    // ------------------------------------------------------------------
    // Attribute and JavaScript string escapes
    // ------------------------------------------------------------------

    public static final Payload QUOTE_SINGLE_BREAKOUT = payload("QUOTE_BREAKOUT", "single-quote",
            "');" + SENTINEL_FUNCTION + "('q');//",
            "escape from a single-quoted JavaScript string literal in an event handler");

    public static final Payload QUOTE_DOUBLE_BREAKOUT = payload("QUOTE_BREAKOUT", "double-quote",
            "\");" + SENTINEL_FUNCTION + "(\"q\");//",
            "escape from a double-quoted JavaScript string literal in an event handler");

    /**
     * Already entity-encoded. Canoe escapes the ampersands, so this should arrive inert; the family
     * exists to prove the encoding is not undone a second time somewhere downstream.
     */
    public static final Payload ENTITY_PRE_ENCODED = payload("ENTITY_BREAKOUT", "pre-encoded",
            "&#39;&#41;&#59;" + SENTINEL_FUNCTION + "&#40;&#39;e&#39;&#41;&#59;&#47;&#47;",
            "double-decoding, if any exists");

    public static final Payload ATTR_DOUBLE_QUOTE_BREAKOUT = payload("ATTR_BREAKOUT", "double-quoted-attr",
            "\" onmouseover=\"" + SENTINEL_FUNCTION + "('a')",
            "termination of a double-quoted attribute value");

    public static final Payload ATTR_SINGLE_QUOTE_BREAKOUT = payload("ATTR_BREAKOUT", "single-quoted-attr",
            "' onmouseover='" + SENTINEL_FUNCTION + "('a')",
            "termination of a single-quoted attribute value");

    public static final Payload ATTR_UNQUOTED_BREAKOUT = payload("ATTR_BREAKOUT", "unquoted-attr",
            "x onmouseover=" + SENTINEL_FUNCTION + "('a')",
            "termination of an unquoted attribute value");

    // ------------------------------------------------------------------
    // URL schemes
    // ------------------------------------------------------------------

    public static final Payload JS_URL = payload("JS_URL", "plain",
            "javascript:" + SENTINEL_FUNCTION + "('u')",
            "a javascript: URL in href, xlink:href, action or formaction");

    public static final Payload JS_URL_MIXED_CASE = payload("JS_URL", "mixed-case",
            "JaVaScRiPt:" + SENTINEL_FUNCTION + "('u')",
            "case-insensitive scheme matching");

    public static final Payload JS_URL_TAB_SPLIT = payload("JS_URL", "tab-split",
            "java\tscript:" + SENTINEL_FUNCTION + "('u')",
            "schemes split by a character browsers strip before parsing");

    public static final Payload JS_URL_NEWLINE_SPLIT = payload("JS_URL", "newline-split",
            "java\nscript:" + SENTINEL_FUNCTION + "('u')",
            "schemes split by a newline");

    public static final Payload JS_URL_LEADING_SPACE = payload("JS_URL", "leading-space",
            " javascript:" + SENTINEL_FUNCTION + "('u')",
            "leading whitespace browsers trim before scheme detection");

    public static final Payload JS_URL_LEADING_CONTROL = payload("JS_URL", "leading-control",
            ch(0x01) + "javascript:" + SENTINEL_FUNCTION + "('u')",
            "leading control characters browsers strip before scheme detection");

    /**
     * The three prefix obfuscations Appendix A &sect;A.4 lists and the corpus had no payload for.
     *
     * <p>All three are expected to be neutralised, and it matters <em>why</em>, because each names a
     * different property of {@code html()}. The entity form proves the parser decodes exactly once:
     * {@code html()} escapes the ampersand to {@code &amp;}, so what the URL parser receives is the
     * eight literal characters {@code &#106;avascript} and not a {@code j}. The percent form proves
     * no consumer percent-decodes before scheme detection. The NUL form is the {@code \xNN} accident
     * the tab and newline splits already document, reached through the one control character that is
     * most often special-cased.
     *
     * <p>They are worth carrying anyway. Under {@code url()} they are safe because the colon is
     * escaped, and under {@code html()} they are safe for the three separate reasons above — so if
     * {@code html()} is ever changed to emit named or numeric references for {@code &} or {@code %},
     * or to pass controls through, these rows say so immediately.
     */
    public static final Payload JS_URL_ENTITY_DECIMAL = payload("JS_URL", "entity-decimal",
            "&#106;avascript:" + SENTINEL_FUNCTION + "('u')",
            "a scheme whose first letter is written as a decimal character reference");

    public static final Payload JS_URL_PERCENT_ENCODED = payload("JS_URL", "percent-encoded",
            "%6Aavascript:" + SENTINEL_FUNCTION + "('u')",
            "a scheme whose first letter is percent-encoded");

    public static final Payload JS_URL_NUL_SPLIT = payload("JS_URL", "nul-split",
            "java" + ch(0x00) + "script:" + SENTINEL_FUNCTION + "('u')",
            "a scheme split by a NUL, which some parsers drop before scheme detection");

    /**
     * A script-bearing scheme from {@code VerdictEvaluator.SCRIPT_BEARING_SCHEMES} that no case
     * reached. {@code view-source:} is the interesting one of the four: it takes a nested URL, so it
     * is simultaneously a scheme test and an off-origin test, and it is the shape a scheme denylist
     * is most likely to forget.
     */
    public static final Payload VIEW_SOURCE_URL = payload("JS_URL", "view-source",
            "view-source:https://" + SENTINEL_HOST + "/x",
            "a scheme that carries a second URL, and which no denylist of eight names remembers");

    public static final Payload VBSCRIPT_URL = payload("JS_URL", "vbscript",
            "vbscript:" + SENTINEL_FUNCTION + "('u')",
            "a legacy scheme Canoe's prefix table does not list");

    public static final Payload DATA_URL_HTML = payload("JS_URL", "data-html",
            "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
            "a data: URL carrying markup");

    public static final Payload PROTOCOL_RELATIVE = payload("PROTOCOL_RELATIVE", "slashes",
            "//" + SENTINEL_HOST + "/x.js",
            "off-origin resource loading with no scheme - every character of it is legal in an"
                    + " authority, so url() emits it unchanged");

    public static final Payload PROTOCOL_RELATIVE_BACKSLASH = payload("PROTOCOL_RELATIVE", "backslash",
            "/\\" + SENTINEL_HOST + "/x.js",
            "the backslash form browsers normalise to a protocol-relative URL");

    /**
     * The other backslash spelling. {@code UrlOracleTest} and the oracle's own table have pinned
     * {@code \\attacker.invalid/x.js} since the oracle was hardened, but no corpus case ever rendered
     * it — so the rule "backslash is a path separator for a special scheme" was asserted about the
     * oracle and never about Canoe. It is a distinct shape from {@code PROTOCOL_RELATIVE_BACKSLASH}
     * ({@code /\host}): that one starts with a real slash, this one does not.
     */
    public static final Payload PROTOCOL_RELATIVE_DOUBLE_BACKSLASH =
            payload("PROTOCOL_RELATIVE", "double-backslash",
                    "\\\\" + SENTINEL_HOST + "/x.js",
                    "the all-backslash form of a protocol-relative URL");

    public static final Payload ABSOLUTE_OFFSITE_HTTPS = payload("ABSOLUTE_OFFSITE", "https",
            "https://" + SENTINEL_HOST + "/x.js",
            "off-origin resource loading - https is on url()'s scheme allowlist, so the URL and its"
                    + " off-origin host survive the parse intact");

    public static final Payload ABSOLUTE_OFFSITE_UPPERCASE = payload("ABSOLUTE_OFFSITE", "uppercase-scheme",
            "HTTPS://" + SENTINEL_HOST + "/x.js",
            "an uppercase scheme, which schemes being case-insensitive makes exactly as off-origin"
                    + " as its lowercase sibling. The old case-sensitive regex missed it and escaped"
                    + " the colon by accident; R12 normalises it, so it reaches the sink live under"
                    + " F6 now - suppressed on the six resource sinks R9 origin-filters, and"
                    + " ACCEPTED_RESIDUAL on the open-redirect and referrer sinks R9 does not");

    public static final Payload ABSOLUTE_OFFSITE_USERINFO = payload("ABSOLUTE_OFFSITE", "userinfo",
            "https://trusted.example@" + SENTINEL_HOST + "/x.js",
            "a host-position '@' - url() escapes it to %40, which puts a forbidden code point"
                    + " inside the host and makes the URL fail to parse rather than reach the host");

    // ------------------------------------------------------------------
    // CSS
    // ------------------------------------------------------------------

    public static final Payload CSS_OVERLAY = payload("CSS_INJECTION", "overlay",
            "red;position:fixed;top:0;left:0;width:100%;height:100%;z-index:99999"
                    + ";background:url(//" + SENTINEL_HOST + "/beacon)",
            "a full-viewport clickjacking overlay that also beacons out");

    public static final Payload CSS_URL_BEACON = payload("CSS_INJECTION", "url-beacon",
            "red;background:url(//" + SENTINEL_HOST + "/beacon)",
            "resource loading from an attacker origin through CSS");

    public static final Payload CSS_IMPORT = payload("CSS_IMPORT", "import",
            "red}@import url(//" + SENTINEL_HOST + "/s.css);a{color:red",
            "stylesheet inclusion from a <style> element body");

    public static final Payload CSS_EXPRESSION = payload("CSS_INJECTION", "expression",
            "expression(" + SENTINEL_FUNCTION + "('css'))",
            "script execution on legacy engines");

    // ------------------------------------------------------------------
    // Markup-bearing and navigation sinks
    // ------------------------------------------------------------------

    public static final Payload SRCDOC_MARKUP = payload("SRCDOC_MARKUP", "img-onerror",
            "<img src=x onerror=" + SENTINEL_FUNCTION + "('srcdoc')>",
            "same-origin script execution inside an iframe - srcdoc needs double encoding");

    public static final Payload META_REFRESH = payload("META_REFRESH", "redirect",
            "0;url=//" + SENTINEL_HOST + "/target",
            "a forced top-level redirect to an attacker origin");

    public static final Payload BASE_HIJACK = payload("BASE_HIJACK", "protocol-relative",
            "//" + SENTINEL_HOST + "/",
            "retargeting of every subsequent relative URL on the page");

    /**
     * Policy tokens, for the attributes whose decoded value the HTML parser acts on as a directive
     * (F20). The point of the family is <em>verbatim arrival</em>, not that each token is meaningful
     * in each attribute: a case gives all three to whichever policy attribute it targets, and its note
     * names the concrete abuse for that attribute. What the three have in common is that they are
     * built only from letters, digits, hyphens, underscores and a space — the characters
     * {@code html()} either passes naked or turns into a character reference the parser puts straight
     * back.
     */
    public static final Payload POLICY_SANDBOX_ESCAPE = payload("POLICY_OVERRIDE", "sandbox-escape",
            "allow-scripts allow-same-origin",
            "removal of an iframe sandbox's script and origin restrictions");

    public static final Payload POLICY_REL_OPENER = payload("POLICY_OVERRIDE", "rel-opener",
            "opener",
            "re-enabling window.opener on a target=_blank link the author meant to be noopener");

    public static final Payload POLICY_TARGET_BLANK = payload("POLICY_OVERRIDE", "target-blank",
            "_blank",
            "retargeting a navigation or form submission into a new browsing context");

    public static final Payload DOM_CLOBBER_LOCATION = payload("DOM_CLOBBER", "location",
            "location",
            "scripts that read document.location through a clobbered named element");

    public static final Payload DOM_CLOBBER_BODY = payload("DOM_CLOBBER", "body",
            "body",
            "scripts that trust document.body");

    // ------------------------------------------------------------------
    // Encoder edge cases
    // ------------------------------------------------------------------

    public static final Payload UNICODE_ASTRAL = payload("UNICODE_EDGE", "astral",
            "grin" + ch(0xd83d) + ch(0xde00) + "end",
            "code points above the BMP, which must emit one reference each");

    public static final Payload UNICODE_LONE_SURROGATE = payload("UNICODE_EDGE", "lone-surrogate",
            "lone" + ch(0xd800) + "end",
            "an unpaired high surrogate");

    public static final Payload UNICODE_LINE_SEPARATORS = payload("UNICODE_EDGE", "line-separators",
            "a" + ch(0x2028) + "b" + ch(0x2029) + "c",
            "U+2028 and U+2029, which terminate a line in JavaScript source");

    public static final Payload UNICODE_RTL_OVERRIDE = payload("UNICODE_EDGE", "rtl-override",
            "a" + ch(0x202e) + "b",
            "a right-to-left override, which reorders displayed text");

    public static final Payload UNICODE_HOMOGLYPH_COLON = payload("UNICODE_EDGE", "homoglyph-colon",
            "javascript" + ch(0xa789) + SENTINEL_FUNCTION + "('u')",
            "U+A789, a colon homoglyph the prefix scanner does not treat as a colon");

    public static final Payload UNICODE_FULLWIDTH_COLON = payload("UNICODE_EDGE", "fullwidth-colon",
            "javascript" + ch(0xff1a) + SENTINEL_FUNCTION + "('u')",
            "U+FF1A, the fullwidth colon");

    public static final Payload CONTROL_NUL = payload("CONTROL_CHARS", "nul",
            "a" + ch(0x00) + "b",
            "a NUL, which some parsers drop and others treat as U+FFFD");

    public static final Payload CONTROL_LOW = payload("CONTROL_CHARS", "c0",
            "a" + ch(0x01) + ch(0x1f) + "b",
            "C0 controls other than tab, CR and LF");

    public static final Payload CONTROL_DEL = payload("CONTROL_CHARS", "del",
            "a" + ch(0x7f) + "b",
            "DEL, which is not below 0x20 and so takes a different encoder branch");

    public static final Payload LENGTH_AT_TAGNAME_LIMIT = payload("LENGTH_STRESS", "at-tagname-limit",
            repeat('a', Canoe.MAX_TAGNAME_LEN - 1),
            "the MAX_TAGNAME_LEN boundary");

    public static final Payload LENGTH_OVER_TAGNAME_LIMIT = payload("LENGTH_STRESS", "over-tagname-limit",
            repeat('a', Canoe.MAX_TAGNAME_LEN + 1),
            "one character past the MAX_TAGNAME_LEN boundary");

    public static final Payload LENGTH_AT_PREFIX_WINDOW = payload("LENGTH_STRESS", "at-prefix-window",
            repeat('a', 10) + ":x",
            "a colon at value index 10, the boundary of the prefix-detection window");

    // ------------------------------------------------------------------
    // Families
    // ------------------------------------------------------------------

    private static final Map<String, List<Payload>> BY_FAMILY = new LinkedHashMap<>();
    private static final List<Payload> ALL = new ArrayList<>();

    static {
        register(INERT_MARKER,
                TAG_IMG_ONERROR, TAG_SCRIPT, TAG_SVG_ONLOAD,
                QUOTE_SINGLE_BREAKOUT, QUOTE_DOUBLE_BREAKOUT, ENTITY_PRE_ENCODED,
                ATTR_DOUBLE_QUOTE_BREAKOUT, ATTR_SINGLE_QUOTE_BREAKOUT, ATTR_UNQUOTED_BREAKOUT,
                JS_URL, JS_URL_MIXED_CASE, JS_URL_TAB_SPLIT, JS_URL_NEWLINE_SPLIT,
                JS_URL_LEADING_SPACE, JS_URL_LEADING_CONTROL,
                JS_URL_ENTITY_DECIMAL, JS_URL_PERCENT_ENCODED, JS_URL_NUL_SPLIT, VIEW_SOURCE_URL,
                VBSCRIPT_URL, DATA_URL_HTML,
                PROTOCOL_RELATIVE, PROTOCOL_RELATIVE_BACKSLASH, PROTOCOL_RELATIVE_DOUBLE_BACKSLASH,
                ABSOLUTE_OFFSITE_HTTPS, ABSOLUTE_OFFSITE_UPPERCASE, ABSOLUTE_OFFSITE_USERINFO,
                CSS_OVERLAY, CSS_URL_BEACON, CSS_IMPORT, CSS_EXPRESSION,
                SRCDOC_MARKUP, META_REFRESH, BASE_HIJACK,
                POLICY_SANDBOX_ESCAPE, POLICY_REL_OPENER, POLICY_TARGET_BLANK,
                DOM_CLOBBER_LOCATION, DOM_CLOBBER_BODY,
                UNICODE_ASTRAL, UNICODE_LONE_SURROGATE, UNICODE_LINE_SEPARATORS,
                UNICODE_RTL_OVERRIDE, UNICODE_HOMOGLYPH_COLON, UNICODE_FULLWIDTH_COLON,
                CONTROL_NUL, CONTROL_LOW, CONTROL_DEL,
                LENGTH_AT_TAGNAME_LIMIT, LENGTH_OVER_TAGNAME_LIMIT, LENGTH_AT_PREFIX_WINDOW);
    }

    private Payloads() {
    }

    /** Every payload in the catalogue, in declaration order. */
    public static List<Payload> all() {
        return Collections.unmodifiableList(ALL);
    }

    /** Every payload in one family, e.g. {@code family("JS_URL")}. */
    public static List<Payload> family(String name) {
        List<Payload> result = BY_FAMILY.get(name);
        if (result == null) {
            throw new IllegalArgumentException("No such payload family: " + name
                    + " (known: " + BY_FAMILY.keySet() + ")");
        }
        return Collections.unmodifiableList(result);
    }

    /** The union of several families, for cases that face more than one kind of attack. */
    public static List<Payload> families(String... names) {
        List<Payload> result = new ArrayList<>();
        for (String name : names) {
            result.addAll(family(name));
        }
        return result;
    }

    /** Every family name, in declaration order. */
    public static List<String> familyNames() {
        return Collections.unmodifiableList(new ArrayList<>(BY_FAMILY.keySet()));
    }

    private static Payload payload(String family, String slug, String value, String reaches) {
        return new Payload(family, slug, value, reaches);
    }

    private static void register(Payload... payloads) {
        Set<String> ids = new LinkedHashSet<>();
        for (Payload payload : payloads) {
            if (!ids.add(payload.id())) {
                throw new IllegalStateException("Duplicate payload id: " + payload.id());
            }
            ALL.add(payload);
            BY_FAMILY.computeIfAbsent(payload.family(), key -> new ArrayList<>()).add(payload);
        }
    }

    /**
     * A one-character string from a code unit. Payloads carry NULs, lone surrogates and
     * bidirectional overrides; building them this way keeps this source file pure ASCII, so it
     * cannot be corrupted by a compiler running under a non-UTF-8 default charset.
     */
    private static String ch(int codeUnit) {
        return String.valueOf((char) codeUnit);
    }

    private static String repeat(char c, int count) {
        char[] chars = new char[count];
        Arrays.fill(chars, c);
        return new String(chars);
    }
}
